AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MWA_VPC
  # Subnets
  SubnetPublicAzA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.32.0/20
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MWA_SUBNET_PUBLIC_AZ_A
  SubnetPrivateAzA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/19
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MWA_SUBNET_PRIVATE_AZ_A
  SubnetPublicAzB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/20
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MWA_SUBNET_PUBLIC_AZ_B
  SubnetPrivateAzB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.64.0/19
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - '1'
        - !GetAZs
          Ref: AWS::Region
      Tags:
        - Key: Name
          Value: MWA_SUBNET_PRIVATE_AZ_B

  # Public Subnet configuration
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MWA_IGW
  InternetGatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Name
          Value: MWA_ROUTE_TABLE
  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref 'RouteTable'
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref 'InternetGateway'
  SubnetPublicAzAToRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref 'RouteTable'
      SubnetId: !Ref 'SubnetPublicAzA'
  SubnetPublicAzBToRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref 'RouteTable'
      SubnetId: !Ref 'SubnetPublicAzB'

  # NAT Gateway for Private subnet
  PrivateSubnetsRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Name
          Value: MWA_PRIVATE_SUBNETS_ROUTE_TABLE
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 'vpc'
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: # !Ref 'EIP' would return IP Address instead of logical resource name
        Fn::GetAtt:
          - EIP
          - AllocationId
      SubnetId: !Ref 'SubnetPrivateAzA'
  NATRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref 'PrivateSubnetsRouteTable'
      NatGatewayId: !Ref 'NATGateway'
      DestinationCidrBlock: 0.0.0.0/0

  # EC2 Instances
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Web Server Security Group'
      VpcId: !Ref 'VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-97785bed'
      KeyName: 'mwa-test'
      InstanceType: 't2.nano'
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref 'WebServerSecurityGroup'
          SubnetId: !Ref 'SubnetPublicAzA'
      Tags:
        - Key: Name
          Value: MWA_WebServer

